/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import com.citahub.cita.protocol.CITAj;
import com.citahub.cita.protocol.core.DefaultBlockParameter;
import com.citahub.cita.protocol.core.methods.request.Transaction;
import com.citahub.cita.protocol.core.methods.response.AppMetaData;
import com.citahub.cita.protocol.http.HttpService;

import java.io.IOException;
import java.math.BigInteger;
import java.util.Random;

public class App {
    public static void main(String[] args) throws IOException {
	CITAj citaService = CITAj.build(new HttpService("http://x.x.x.x:1337")); 		// http://x.x.x.x:1337 需要改为节点的RPC接口或者缓存服务器接口
	String to = "0xa00f716b4925e4fe59d9238766e94219d22daa6e";
	Random r = new Random();
	String nonce = String.valueOf(Math.abs(r.nextLong()));
	AppMetaData appMetaData;
	appMetaData = citaService.appMetaData(DefaultBlockParameter.valueOf("latest")).send();
	long currentHeight = citaService.appBlockNumber().send().getBlockNumber().longValue();
	long validUntilBlock = currentHeight + 80;
	long quota = 1000000000;
	int version = appMetaData.getAppMetaDataResult().getVersion();
	BigInteger chainId = BigInteger.valueOf(1);
	String value = "1000000000000000000000";
	String data = "0x65766964656e63653d65766964656e63617368646630386165342674696d657374616d703d3137383332353130333237";


	Transaction tx = Transaction.createFunctionCallTransaction(to, nonce, quota, validUntilBlock, version, chainId, value, data);
	String privateKey = "0xf10a049eaa8390612ea7f87dcc79cbe82538807b0a31ff33126cf4473f5ed1f3";
	String rawTx = tx.sign(privateKey);
	String txHash  = citaService.appSendRawTransaction(rawTx).send().getSendTransactionResult().getHash();

	System.out.printf("txHash");
    }
}
